version: '3.8'

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "${LOGGING_DSN}"

services:
  parking:
    <<: *logging
    image: ${PARKING_SERVICE_IMAGE}
    environment:
      - DB_URL=${RDBS_DSN}
      - DB_USERNAME=${RDBS_USER}
      - DB_PASSWORD=${RDBS_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.apps == true
    ports:
      - target: 8080
        published: ${PARKING_SERVICE_PORT}
        protocol: tcp
        mode: ingress
    healthcheck:
      test: ["curl", "--fail", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 15s
      retries: 5
    networks:
      - poga

networks:
  poga:
    external: true