name: Deploy Environment

on: [push]

env:
  SOURCE_CODE_PATH: ~/poga-deploy

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
    - name: Copy Repository to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_REMOTE_HOST }}
        username: ${{ secrets.DEPLOY_REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: true
        source: "configs/*,stacks/*,scripts/*"
        target: ${{ env.SOURCE_CODE_PATH }}
    - name: Export Telegram Bot Token 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_REMOTE_HOST }}
        username: ${{ secrets.DEPLOY_REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            export TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
            cd ${{ env.SOURCE_CODE_PATH }}/configs/monitoring/alertmanager
            sed -i "s|bot_token: ''|bot_token: '${TELEGRAM_BOT_TOKEN}'|g" alertmanager-config.yml
    - name: Save .env variables to file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_REMOTE_HOST }}
        username: ${{ secrets.DEPLOY_REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "${{ vars.SETTINGS }}" | tr -d '\r' > ${{ env.SOURCE_CODE_PATH }}/stacks/.env
          echo "${{ secrets.GRAFANA_USER }}" >> ${{ env.SOURCE_CODE_PATH }}/stacks/.env
          echo "${{ secrets.GRAFANA_PASSWORD }}" >> ${{ env.SOURCE_CODE_PATH }}/stacks/.env
  deploy:
    needs: delivery
    runs-on: ubuntu-latest
    steps:
      - name: Remove Docker Stacks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_REMOTE_HOST }}
          username: ${{ secrets.DEPLOY_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ${{ env.SOURCE_CODE_PATH }}/scripts/remove-env-stacks.sh
            /bin/sh ${{ env.SOURCE_CODE_PATH }}/scripts/remove-env-stacks.sh
      - name: Run Docker Stacks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_REMOTE_HOST }}
          username: ${{ secrets.DEPLOY_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export $(cat ${{ env.SOURCE_CODE_PATH }}/stacks/.env | xargs) > /dev/null 2>&1
            chmod +x ${{ env.SOURCE_CODE_PATH }}/scripts/run-env-stacks.sh
            /bin/sh ${{ env.SOURCE_CODE_PATH }}/scripts/run-env-stacks.sh